apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: hermes-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    control-plane: controller-manager
