{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermes-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hermes-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "hermes-operator.selectorLabels" . | nindent 4 }}
{{- end }}
